name: CI - Backend + Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [API.Gateway, Customer, Order, Payment, Product, Shipping]
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - run: dotnet restore ${{ matrix.service }}.sln
      - run: dotnet build ${{ matrix.service }}.sln --no-restore
      - run: dotnet test ${{ matrix.service }}.sln --no-build
